name: UPD readme
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install tool
      run: sudo apt install fortune cowsay -y
    - name: gen README.md
      run: |
        echo "Last Update Time: " > README.md
        date >> README.md
        echo "<br>![](https://img.shields.io/badge/%E5%A4%A7%E5%AE%B6-%E5%AE%89%E5%AE%89-green)<br>" >> README.md
        echo "\`\`\`" >> README.md
        fortune | cowsay >> README.md
        echo "\`\`\`" >> README.md
        echo "![](https://github-readme-stats.vercel.app/api?username=chenlitw)" >> README.md
        echo "![](https://github-readme-stats.vercel.app/api/top-langs/?username=chenlitw)" >> README.md
    - name: push
      run: |
        git add .
        git config --global user.email "actions-bot@le37.tw"
        git config --global user.name "actions bot"
        git commit -m "test"
        git push -f
